project_id = "ljpgxealqbhiszweqvyj"

[functions.create-user-with-credentials]
verify_jwt = true

[functions.bootstrap-super-admin]
verify_jwt = false

[functions.reset-bootstrap]
verify_jwt = false

[functions.delete-institute-admins]
verify_jwt = true

[functions.get-batch-status]
verify_jwt = true

[functions.auto-capture-upload]
verify_jwt = true

[functions.backup-batch-images]
verify_jwt = true

[functions.process-pipeline]
verify_jwt = true

[functions.check-low-attendance]
verify_jwt = true

[functions.delete-user-complete]
verify_jwt = true
